// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Server_Final.Models;

namespace Web_Server_Final.Migrations
{
    [DbContext(typeof(WebServerFinalContext))]
    [Migration("20220422124517_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web_Server_Final.Models.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("SportId");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportId = 1,
                            SportName = "Basketball"
                        },
                        new
                        {
                            SportId = 2,
                            SportName = "Football"
                        },
                        new
                        {
                            SportId = 3,
                            SportName = "Soccer"
                        },
                        new
                        {
                            SportId = 4,
                            SportName = "Baseball"
                        },
                        new
                        {
                            SportId = 5,
                            SportName = "Rugby"
                        },
                        new
                        {
                            SportId = 6,
                            SportName = "Tennis"
                        },
                        new
                        {
                            SportId = 7,
                            SportName = "Lacrosse"
                        });
                });

            modelBuilder.Entity("Web_Server_Final.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            City = "Cincinnati",
                            SportId = 2,
                            TeamName = "Bengals"
                        },
                        new
                        {
                            TeamId = 2,
                            City = "Cincinnati",
                            SportId = 4,
                            TeamName = "Reds"
                        },
                        new
                        {
                            TeamId = 3,
                            City = "Miami",
                            SportId = 1,
                            TeamName = "Heat"
                        },
                        new
                        {
                            TeamId = 4,
                            City = "Sacremento",
                            SportId = 1,
                            TeamName = "Kings"
                        },
                        new
                        {
                            TeamId = 5,
                            City = "Atlanta",
                            SportId = 4,
                            TeamName = "Braves"
                        },
                        new
                        {
                            TeamId = 6,
                            City = "Indiana",
                            SportId = 2,
                            TeamName = "Colts"
                        },
                        new
                        {
                            TeamId = 7,
                            City = "Cincinnati",
                            SportId = 3,
                            TeamName = "FC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
